### ISSUE TITLE
[feature request] Add ability to specify location to spawn structure with /spawnstructure 

### ISSUE THREAD

**Issue by Goldenlion5648** [TelepathicGrunt/CommandStructures-Forge#1]
This mod looks awesome! Would have been useful about two weeks ago in a project I was working on.

Would it be possible to add an argument to /spawnstructure to allow specifying where a structure should be generated? This would be very useful for map makers. The default could be the player's position.

Currently using the command in a command block spaws the structure at 0 0.

**Comment by TelepathicGrunt** [comment]
added now in 1.3.0
