### ISSUE TITLE
Dungeons arise compat

### ISSUE THREAD

**Issue by Aabaddon** [TelepathicGrunt/CommandStructures-Forge#5]
Dungeons arise is incredible but really hard to use because if not controlled the structures spawn like crazy lagging the world, i was hoping to be able to create a world without structures and then add em myself with this mod, it kinda works with vanilla structures but it is impossible to make it work with dungeons arise because it doesnt spawn all the pieces in order, it just spawns em by... well by pieces and it is completely impossible to correctly connect them

the thing im asking for is, would it be possible to add a command to generate the whole structure as it would generate in normal worldgen? just... the whole thing not by pieces

**Comment by TelepathicGrunt** [comment]
That’s what vanilla’s /place structure command does. You can use that to spawn structures. That’s why my command for that was removed because vanilla added it themselves

**Comment by Aabaddon** [comment]
oh, im just plain dumb, thanks for the answer
